-- Milo cloud schema: multi-tenant movies+tv table with RLS scoped to auth.uid()

create table if not exists movies (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  rating numeric check (rating >= 1 and rating <= 10),
  genre text,
  date_watched date,
  notes text,
  director text,
  release_year integer,
  type text default 'movie',
  num_seasons integer,
  total_episodes integer,
  created_at timestamptz default now()
);

create index if not exists movies_user_id_idx on movies (user_id);
create index if not exists movies_user_type_idx on movies (user_id, type);

alter table movies enable row level security;

drop policy if exists "owner read"   on movies;
drop policy if exists "owner insert" on movies;
drop policy if exists "owner update" on movies;
drop policy if exists "owner delete" on movies;

create policy "owner read"   on movies for select using (auth.uid() = user_id);
create policy "owner insert" on movies for insert with check (auth.uid() = user_id);
create policy "owner update" on movies for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "owner delete" on movies for delete using (auth.uid() = user_id);
