-- Milo friends + per-item privacy
-- Adds friendships, profiles, an is_public flag on movies, and RLS so
-- accepted friends can read each other's public rows.

create extension if not exists citext;

-- 1. Per-item privacy on movies
alter table movies add column if not exists is_public boolean not null default true;
create index if not exists movies_user_public_idx on movies (user_id, is_public);

-- 2. Profiles
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username citext unique,
  display_name text,
  bio text,
  avatar_url text,
  created_at timestamptz default now()
);

alter table profiles enable row level security;

drop policy if exists "view all profiles" on profiles;
drop policy if exists "insert own profile" on profiles;
drop policy if exists "update own profile" on profiles;

create policy "view all profiles" on profiles for select using (true);
create policy "insert own profile" on profiles for insert with check (auth.uid() = id);
create policy "update own profile" on profiles for update using (auth.uid() = id) with check (auth.uid() = id);

-- 3. Friend requests
create table if not exists friend_requests (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references auth.users(id) on delete cascade,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted','rejected')),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (requester_id, recipient_id),
  check (requester_id <> recipient_id)
);

create index if not exists friend_requests_recipient_idx on friend_requests (recipient_id, status);
create index if not exists friend_requests_requester_idx on friend_requests (requester_id, status);

alter table friend_requests enable row level security;

drop policy if exists "view own requests"          on friend_requests;
drop policy if exists "create requests"            on friend_requests;
drop policy if exists "act on incoming requests"   on friend_requests;
drop policy if exists "cancel own outgoing"        on friend_requests;
drop policy if exists "either side can unfriend"   on friend_requests;

create policy "view own requests" on friend_requests for select
  using (auth.uid() = requester_id or auth.uid() = recipient_id);

create policy "create requests" on friend_requests for insert
  with check (auth.uid() = requester_id);

create policy "act on incoming requests" on friend_requests for update
  using (auth.uid() = recipient_id)
  with check (auth.uid() = recipient_id);

create policy "either side can unfriend" on friend_requests for delete
  using (auth.uid() = requester_id or auth.uid() = recipient_id);

-- 4. Movies SELECT policy for friends — public rows only
drop policy if exists "friends read public movies" on movies;
create policy "friends read public movies" on movies for select using (
  is_public = true
  and exists (
    select 1 from friend_requests fr
    where fr.status = 'accepted'
      and ((fr.requester_id = auth.uid() and fr.recipient_id = movies.user_id)
        or (fr.recipient_id = auth.uid() and fr.requester_id = movies.user_id))
  )
);

-- 5. updated_at trigger
create or replace function update_updated_at() returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists friend_requests_updated_at on friend_requests;
create trigger friend_requests_updated_at
  before update on friend_requests
  for each row execute procedure update_updated_at();

-- 6. Auto-create profile row on signup
create or replace function handle_new_user() returns trigger as $$
begin
  insert into profiles (id) values (new.id) on conflict do nothing;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure handle_new_user();

-- 7. Email lookup RPC (auth.users isn't exposed via PostgREST)
create or replace function find_user_by_email(p_email text)
returns uuid language sql security definer as $$
  select id from auth.users where lower(email) = lower(p_email) limit 1;
$$;
revoke all on function find_user_by_email(text) from public;
grant execute on function find_user_by_email(text) to authenticated;
