-- Persisted Taste Profile: one distilled profile per user per scope, RLS-scoped.
-- scope 'all' = unified movies+TV profile (room left for 'movie'/'tv' later).

create table if not exists taste_profiles (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  scope text not null default 'all',
  profile_json jsonb not null,
  library_signature text,
  model text,
  generated_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (user_id, scope)
);

create index if not exists taste_profiles_user_id_idx on taste_profiles (user_id);

alter table taste_profiles enable row level security;

drop policy if exists "owner read"   on taste_profiles;
drop policy if exists "owner insert" on taste_profiles;
drop policy if exists "owner update" on taste_profiles;
drop policy if exists "owner delete" on taste_profiles;

create policy "owner read"   on taste_profiles for select using (auth.uid() = user_id);
create policy "owner insert" on taste_profiles for insert with check (auth.uid() = user_id);
create policy "owner update" on taste_profiles for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "owner delete" on taste_profiles for delete using (auth.uid() = user_id);
