-- Recommendation feedback: one row per user per (normalized) title per content type.
-- Feeds future rec prompts: 'not_for_me' = durable exclusion + negative signal,
-- 'interested' = positive signal (title also added to watchlist by the UI),
-- 'seen_it' = durable exclusion only.

create table if not exists rec_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  normalized_title text not null,
  content_type text not null default 'movie',
  feedback text not null check (feedback in ('interested', 'not_for_me', 'seen_it')),
  year integer,
  genre text,
  rec_type text,
  model text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (user_id, normalized_title, content_type)
);

create index if not exists rec_feedback_user_id_idx on rec_feedback (user_id);

alter table rec_feedback enable row level security;

drop policy if exists "owner read"   on rec_feedback;
drop policy if exists "owner insert" on rec_feedback;
drop policy if exists "owner update" on rec_feedback;
drop policy if exists "owner delete" on rec_feedback;

create policy "owner read"   on rec_feedback for select using (auth.uid() = user_id);
create policy "owner insert" on rec_feedback for insert with check (auth.uid() = user_id);
create policy "owner update" on rec_feedback for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "owner delete" on rec_feedback for delete using (auth.uid() = user_id);
